paths:
  src:
    path: "../src/"

    styles:
      all : "../src/assets/styles/**/*.styl"
      main: "../src/assets/styles/main.styl"
      path: "../src/assets/styles"

    iconfont: "../src/assets/iconfont/*.svg"

    sprites:
      images:
        all: "../src/assets/images/design/sprite/*"
        path: "../src/assets/images/design/sprite"
      style: "../src/assets/styles/common"

    scripts:
      # all: "../src/assets/scripts/**/*.coffee"
      all: "../src/assets/scripts/**/*.js"
      json: "../src/assets/scripts/**/*.json"
      html: "../src/assets/scripts/**/*.html"

    images:
      all: "../src/assets/images/**/*.*"
      path: "../src/assets/images"
      design:
        path: "../src/assets/images/design"
      content:
        path: "../src/assets/images/content"
      svg:
        path: "../src/assets/images/svg/*.svg"

    templates:
      all: "../src/templates/**/*.jade"
      path: "../src/templates"
      blocks:
        all: "../src/templates/blocks/**/*.jade"
        path: "../src/templates/blocks"
      pages:
        all: "../src/templates/pages/**/*.jade"
        path: "../src/templates/pages"

  built:
    path: "../built/"

    styles:
      all: "../built/assets/styles/**/*.css"
      path: "../built/assets/styles"
      svg:
        path: "../../styles/svg.css"

    iconfont:
      font: "../built/assets/fonts/iconfont/"

    scripts:
      all: "../built/assets/scripts/**/*.js"
      path: "../built/assets/scripts/"

    images:
      all: "../built/assets/images/**/*.*"
      path: "../built/assets/images"
      design:
        path: "../built/assets/images/design"
      content:
        path: "../built/assets/images/content"
      svg:
        path: "../built/assets/images/svg"
        sprite:
          path: "../images/svg/svg/sprite.svg"

    libs:
      path: '../built/assets/libs/'
